services:
  ollama:
    build:
      context: .
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    networks:
      - restricted_net
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]

  socat:
    image: alpine/socat
    container_name: socat
    networks:
      - restricted_net
      - unrestricted_net
    ports:
      - "11434:11434"
    command: TCP-LISTEN:11434,fork,reuseaddr TCP:ollama:11434

volumes:
  ollama-data:

networks:
  restricted_net:
    driver: bridge
    internal: true

  unrestricted_net:
    driver: bridge
